name: Verify
on:
  push:
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  verify:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      # for EnricoMi/publish-unit-test-result-action
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Package application
        run: ./mvnw -B -V -ntp package
      - name: Install playwright
        run: |
          npm install
          npx playwright install chromium --with-deps
          npx playwright install-deps
      - if: ${{ env.ACT }}
        name: Install ACT dependencies (only in ACT)
        run: |
          for i in PATH ; do
              H=`eval 'echo $'$i`
              echo "export $i='"$H"'" >> vars.sh
          done
          sudo apt-get update -qq
          sudo apt-get install -qq -y vim iputils-ping curl netcat-openbsd net-tools
        shell: bash
      - name: Test flow & hilla
        run: ./mvnw -B -V -ntp verify -Pit
      - if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: tests-report
          path: target/**-reports
          retention-days: 30
      - if: ${{ always() && !env.ACT }}
        name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "target/*-reports/TEST*.xml"
